version: '3.7'

services:

  idp_postgres:
    hostname: "${DB_HOSTNAME}"
    image: postgres:14.2-alpine
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    # networks:
    #   - rest_api_network
    #   - db_management_network
    restart: always
    healthcheck:
      # test: ["CMD", "pg_isready -U postgres"]
      test: pg_isready -U postgres
      interval: 5s
      timeout: 2s
      retries: 15

###########################################################################

  idp_rabbitmq:
    hostname: "${MQ_HOSTNAME}"
    image: rabbitmq:3.10-management
    ports:
      - "${MQ_PORT}:${MQ_PORT}"
      - "${MQ_PORT_MANAGEMENT}:${MQ_PORT_MANAGEMENT}"
    environment:
      - "RABBITMQ_DEFAULT_USER=${MQ_USERNAME}"
      - "RABBITMQ_DEFAULT_PASS=${MQ_PASSWORD}"
    restart: always
    healthcheck:
      # test: ["CMD", "curl", "-f", "http://idp_rabbitmq:15672"]
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 2s
      retries: 15

###########################################################################

  idp_keyclock:
    hostname: "${KEY_CLOCK_HOSTNAME}"
    image: jboss/keycloak:16.1.1
    ports:
      - "${KEY_CLOCK_PORT_IN}:${KEY_CLOCK_PORT_OUT}"
      - "${KEY_CLOCK_PORT_ADMIN}:${KEY_CLOCK_PORT_ADMIN}"
      - "${KEY_CLOCK_PORT_AUX}:${KEY_CLOCK_PORT_AUX}"
    environment:
      - "DB_VENDOR=POSTGRES"
      - "DB_ADDR=${DB_HOSTNAME}"
      - "DB_PORT=${DB_PORT}"
      - "DB_DATABASE=${DB_NAME}"
      - "DB_SCHEMA=${DB_SCHEMA}"
      - "KEYCLOAK_USER=${KEY_CLOCK_USERNAME}"
      - "KEYCLOAK_PASSWORD=${KEY_CLOCK_PASSWORD}"
      - "DB_USER=${DB_USERNAME}"
      - "DB_PASSWORD=${DB_PASSWORD}"
    depends_on:
      idp_postgres:
        condition: service_healthy
    volumes:
      - ./keyclock_config_volume/:/tmp
    restart: always
    healthcheck:
      # test: ["CMD", "curl", "-f", "http://idp_keyclock:8180"]
      # test: ["CMD", "curl", "-f", "http://localhost:8080/auth/"]
      test: curl -f http://localhost:8080/auth/
      interval: 5s
      timeout: 2s
      retries: 15

###########################################################################

  idp_spring_boot_api:
    image: 127.0.0.1:8888/idp_spring_boot_api
    ports:
      - "${SERVER_API_PORT}:${SERVER_API_PORT}"
    depends_on:
      idp_postgres:
        condition: service_healthy
      idp_rabbitmq:
        condition: service_healthy
      idp_keyclock:
        condition: service_healthy
    build:
      context: ../proiect_refugiati_api
      dockerfile: refugiati.Dockerfile
    restart: always

